using System.Threading;
using Cysharp.Threading.Tasks;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace BK.UI
{
    /// <summary>One- or two-button modal. Prefab generated by BK > Framework > Generate UI Prefabs.</summary>
    public sealed class MessagePopupView : UIViewBase, IUIView<MessageRequest>
    {
        [SerializeField] private TMP_Text _title;
        [SerializeField] private TMP_Text _body;
        [SerializeField] private Button _confirm;
        [SerializeField] private TMP_Text _confirmLabel;
        [SerializeField] private Button _cancel;
        [SerializeField] private TMP_Text _cancelLabel;
        [SerializeField] private Button _background;

        private readonly UniTaskCompletionSource<bool> _result = new();
        private MessageRequest _request;

        public UniTask<bool> Result => _result.Task;

        public void SetArgs(MessageRequest args) => _request = args;

        public override UniTask OnInitializeAsync(CancellationToken cancellationToken)
        {
            _title.text = _request.Title ?? "";
            _body.text = _request.Body ?? "";
            _confirmLabel.text = _request.ConfirmText ?? "OK";
            _cancel.gameObject.SetActive(_request.IsConfirm);
            if (_request.IsConfirm)
                _cancelLabel.text = _request.CancelText;
            _confirm.onClick.AddListener(() => _result.TrySetResult(true));
            _cancel.onClick.AddListener(() => _result.TrySetResult(false));
            _background.onClick.AddListener(() => { if (!_request.Forced) _result.TrySetResult(false); });
            return base.OnInitializeAsync(cancellationToken);
        }

        public override bool OnBackRequested()
        {
            if (!_request.Forced)
                _result.TrySetResult(false);
            // Always consumed: the presenter closes us; the service must not pop us mid-await.
            return true;
        }

        /// <summary>Used by the editor generator to wire the prefab.</summary>
        public void Bind(TMP_Text title, TMP_Text body, Button confirm, TMP_Text confirmLabel, Button cancel, TMP_Text cancelLabel, Button background)
        {
            _title = title;
            _body = body;
            _confirm = confirm;
            _confirmLabel = confirmLabel;
            _cancel = cancel;
            _cancelLabel = cancelLabel;
            _background = background;
        }
    }
}
