using System.Threading;
using Cysharp.Threading.Tasks;
using TMPro;
using UnityEngine;

namespace BK.UI
{
    /// <summary>Short non-blocking text on the System layer. Prefab generated by BK > Framework > Generate UI Prefabs.</summary>
    public sealed class ToastView : UIViewBase, IUIView<string>
    {
        [SerializeField] private TMP_Text _text;
        private string _message;

        public void SetArgs(string args) => _message = args;

        public override UniTask OnInitializeAsync(CancellationToken cancellationToken)
        {
            _text.text = _message ?? "";
            return base.OnInitializeAsync(cancellationToken);
        }

        public override bool OnBackRequested() => true;

        public void Bind(TMP_Text text) => _text = text;
    }
}
